feat: we can use kubectl logs and docker logs review apisix container's logs.
apache/apisix-docker pull request #128
Opened 2021-02-05 09:06 UTC by sober-wang

we can use `kubectl logs` and `docker logs` review apisix container's logs

```shell
kubectl -n <YOUR_NAMEPSACES> logs <APISIX_POD>
docker logs <APISIX_CONTAINERS>
```

2021-02-13 06:14 UTC, imjoey requested changes

2021-02-13 06:14 UTC, imjoey commented on alpine/Dockerfile
> +# apisix's logs will output the stdout and stderr. we can use commend `kubectl logs` and `docker logs` review apisix's logs
```suggestion
# APISIX's logs will output the stdout and stderr. We can use command `kubectl logs` and `docker logs` to review APISIX's logs
```

2021-02-13 06:15 UTC, imjoey commented
Hi @sober-wang , thank you. Could you please add relevant test cases in CI to check the logs output? That would make the PR much reliable. Thanks.

2021-02-13 09:29 UTC, sober-wang commented
I know your mean's. But can you help me ,how to create a test cases in CI.

2021-02-18 03:59 UTC, imjoey commented
> I know your mean's. But can you help me ,how to create a test cases in CI.

Hi @sober-wang , you could try login via curl and then see if `docker logs` contains relevant logs,  please refer to https://github.com/apache/apisix-dashboard/blob/8e1854704d5545f7574fb69fe2710f19871279fd/.github/workflows/backend-unit-test.yml#L55-L61 for example.

BTW: I checked out your code in my local MacOS, but unfortunately I was not able to see continuous logs output via `docker logs`. Of course, perhaps there's something wrong with my environment. 😄 So additional checks in CI would be better.

2021-02-18 11:42 UTC, sober-wang commented
> > I know your mean's. But can you help me ,how to create a test cases in CI.
> 
> Hi @sober-wang , you could try login via curl and then see if `docker logs` contains relevant logs, please refer to https://github.com/apache/apisix-dashboard/blob/8e1854704d5545f7574fb69fe2710f19871279fd/.github/workflows/backend-unit-test.yml#L55-L61 for example.
> 
> BTW: I checked out your code in my local MacOS, but unfortunately I was not able to see continuous logs output via `docker logs`. Of course, perhaps there's something wrong with my environment. 😄 So additional checks in CI would be better.

maybe , you should do something look like this
```shell
cd  apisix-docker/centos
docker build -t newapisix-image:20210218 
docker run -d -p 9080:9080 --name=newapisix newapisix-image:20210218
# next used 
docker logs newapisix 
# you'll see the apisix logs in stdout
```

2021-02-19 06:49 UTC, gxthrj commented
I added a CI in #133 , we can merge this PR after #133 merged.

2021-02-25 04:40 UTC, gxthrj commented
We can continue to review this pr, @sober-wang Need to modify the document format as @imjoey  suggest.
As #133  has been merged, we need to rebase master.

2021-04-01 01:14 UTC, spacewander commented
Solved.

2021-04-01 01:14 UTC, closed without merging