feat: added issue-template
apache/apisix-docker pull request #183
Opened 2021-06-07 03:16 UTC by iamayushdas

fixed: #182 (Added issue template)

2021-06-07 09:03 UTC, iamayushdas commented
cc @Yiyiyimu

2021-06-07 18:25 UTC, Yiyiyimu requested changes

2021-06-07 18:25 UTC, Yiyiyimu commented on .github/workflows/ISSUE_TEMPLATE/bug-report.md
> +* apisix-docker version, you have:
apisix docker version is enough

2021-06-07 18:25 UTC, Yiyiyimu commented on .github/workflows/ISSUE_TEMPLATE/config.yml
> +    about: Ask questions or discuss with other community members about Apache APISIX
newline missing

2021-06-08 03:24 UTC, iamayushdas commented on .github/workflows/ISSUE_TEMPLATE/config.yml
> +    about: Ask questions or discuss with other community members about Apache APISIX
okay sir

2021-06-08 18:33 UTC, Yiyiyimu approved these changes

2021-06-08 18:33 UTC, Yiyiyimu commented on .github/workflows/ISSUE_TEMPLATE/bug-report.md
> +* apisix-docker version, you have:
```suggestion
* apisix-docker version:
```

2021-06-10 01:02 UTC, tokers approved these changes

2021-06-10 02:55 UTC, merged