feat: upgrade APISIX to 2.10.2
apache/apisix-docker pull request #247
Opened 2021-11-19 09:14 UTC by tzssangglass

Signed-off-by: tzssangglass <tzssangglass@gmail.com>

2021-11-19 09:18 UTC, tzssangglass commented
wait for rpm ready

2021-11-19 09:31 UTC, tokers approved these changes

2021-11-19 09:53 UTC, spacewander commented on centos/Dockerfile
> +ARG APISIX_VERSION=2.10.2.1
```suggestion
ARG APISIX_VERSION=2.10.2
```

2021-11-20 13:05 UTC, lilien1010 approved these changes
LGTM

2021-11-21 06:14 UTC, tao12345666333 approved these changes

2021-11-21 13:46 UTC, spacewander requested changes
Wait for rpm.

2021-11-22 02:38 UTC, spacewander approved these changes

2021-11-22 02:38 UTC, merged