feat: add build for platform=redhat with ubi based image
apache/apisix-docker pull request #462
Opened 2023-05-19 09:22 UTC by Revolyssup

Fixes https://github.com/apache/apisix/issues/9454

Note: The path to rpm package needs to be clarified to make sure that the rpm package based on ubi is published on 
https://repos.apiseven.com/packages/redhat/apache-apisix-repo-1.0-1.noarch.rpm

2023-05-19 09:30 UTC, tao12345666333 requested changes

2023-05-19 09:30 UTC, tao12345666333 commented on redhat/Dockerfile
> +RUN yum install -y https://repos.apiseven.com/packages/redhat/apache-apisix-repo-1.0-1.noarch.rpm \
If you don't have this file, you can directly add the configuration file in the /etc/yum.repos.d directory.

2023-05-19 09:30 UTC, tao12345666333 commented on Makefile
> +.PHONY: build-on-centos
typo?

2023-05-19 09:51 UTC, Revolyssup commented on Makefile
> +.PHONY: build-on-centos
yes. fixing it

2023-05-22 04:32 UTC, Revolyssup commented
Overriden by https://github.com/apache/apisix-docker/pull/463

2023-05-22 06:39 UTC, tao12345666333 approved these changes

2023-05-22 06:45 UTC, Sn0rt commented on redhat/yum.repos.d/apache-apisix.repo
> +enabled_metadata=1
new line EOF

2023-05-22 06:45 UTC, Sn0rt commented on redhat/yum.repos.d/openresty.repo
> +enabled_metadata=1
new line EOF

2023-05-22 06:47 UTC, Revolyssup commented on redhat/yum.repos.d/apache-apisix.repo
> +enabled_metadata=1
@Sn0rt You want me to add a new line EOF?

2023-05-22 07:12 UTC, tao12345666333 commented
https://github.com/apache/apisix-docker/blob/7dfe5840e7705ccee135f0220b12d369d52d0ca8/.github/workflows/apisix-docker-example-test.yaml you should change this file to run the test.

2023-05-22 07:16 UTC, Revolyssup commented
> https://github.com/apache/apisix-docker/blob/7dfe5840e7705ccee135f0220b12d369d52d0ca8/.github/workflows/apisix-docker-example-test.yaml you should change this file to run the test.

@tao12345666333 done

2023-05-22 07:24 UTC, tao12345666333 approved these changes

2023-05-22 07:38 UTC, Sn0rt approved these changes

2023-05-23 01:15 UTC, leslie-tsang commented on redhat/yum.repos.d/apache-apisix.repo
> +enabled_metadata=1
Yes, Plz.

2023-05-23 01:15 UTC, leslie-tsang commented on redhat/hooks/build
> +# hooks/build
Why we add a build hook here, it seems do the same thing as Makefile do.

2023-05-23 04:21 UTC, Revolyssup commented on redhat/hooks/build
> +# hooks/build
I was also confused about it but since it was present in centos and debian, I added it here. Should I remove?

2023-05-23 05:16 UTC, leslie-tsang commented on redhat/hooks/build
> +# hooks/build
Please check if it was necessary. IMO, it's not.

2023-05-23 05:27 UTC, Revolyssup commented on redhat/hooks/build
> +# hooks/build
@leslie-tsang  You're right. I couldn't find any usage of it in this repo so removed it.

2023-05-24 02:11 UTC, leslie-tsang approved these changes

2023-05-24 02:29 UTC, soulbird commented on redhat/Dockerfile
> +COPY ./yum.repos.d/openresty.repo /etc/yum.repos.d/openresty.repo
We can download this file directly online: https://openresty.org/package/centos/openresty.repo

2023-05-24 02:31 UTC, soulbird commented on redhat/yum.repos.d/apache-apisix.repo
> +[release]
Would it be better if I also upload this file to https://repos.apiseven.com/packages/redhat/ ？

2023-05-24 02:31 UTC, Sn0rt commented on redhat/yum.repos.d/apache-apisix.repo
> +[release]
the CI loss. we this is another task.

2023-05-24 02:32 UTC, Sn0rt commented on redhat/Dockerfile
> +COPY ./yum.repos.d/openresty.repo /etc/yum.repos.d/openresty.repo
https://github.com/api7/apisix-build-tools/issues/304

we will create a new ci to build this rpm package. so I think this modification postpone is acceptable

2023-05-24 02:33 UTC, Sn0rt approved these changes

2023-05-24 03:52 UTC, merged