feat: remove overwrite apisix.yaml
apache/apisix-docker pull request #487
Opened 2023-07-28 06:35 UTC by kamly

from https://github.com/apache/apisix-docker/issues/482

2023-07-28 06:38 UTC, nfrankel approved these changes
Thanks for your contribution!

2023-07-31 02:05 UTC, kamly commented
@soulbird hi, please have a review ~

2023-07-31 02:43 UTC, Sn0rt approved these changes

2023-07-31 11:08 UTC, kamly commented
@nfrankel @Sn0rt , hi I meet two problems

1. if remove overwrite `apisix.yaml`

when docker run with `-e APISIX_STAND_ALONE=true`
```shell
docker run -d --name apache-apisix \
  -p 9080:9080 \
  -e APISIX_STAND_ALONE=true \
  apache/apisix
```

will print warn and error info
```
...
apisix              | 2023/07/31 12:55:13 [warn] 47#47: *11206 [lua] config_yaml.lua:127: wait for more time, context: ngx.timer
apisix              | 2023/07/31 12:55:13 [error] 31#31: *12907 [lua] config_yaml.lua:73: failed to fetch /usr/local/apisix/conf/apisix.yaml attributes: cannot obtain information from file '/usr/local/apisix/conf/apisix.yaml': No such file or directory, context: ngx.timer
...
```

is it as expected ?

2. Unit tests fail. (https://github.com/apache/apisix-docker/actions/runs/5689010648/job/15470480442)

I debugged the unit test and found that it will exit automatically. So executing `curl http://127.0.0.1:9000` will fail

<img width="1568" alt="image" src="https://github.com/apache/apisix-docker/assets/15706085/49246d4d-91db-46d4-8900-ed50bd56bf4f">

2023-07-31 13:02 UTC, nfrankel requested changes
>is it as expected ?

Nope, it's not. Apache APISIX requires the file. So the correct logic must be that **if** the file exists, don't overwrite it; if it does, keep the current behavior

2023-07-31 13:14 UTC, kamly commented
> Nope, it's not. Apache APISIX requires the file. So the correct logic must be that **if** the file exists, don't overwrite it; if it does, keep the current behavior

done

2023-08-01 04:28 UTC, kamly commented
@nfrankel please , look look ~

2023-08-01 06:39 UTC, nfrankel approved these changes

2023-08-02 13:57 UTC, nfrankel commented
> @nfrankel others can review ?

We appreciate your contribution, but please, don't comment to get faster review. People do have other commitments. Hence:

1. It doesn't speed up things
2. It makes people unhappy

Thanks for your understanding.

Besides, one of the check is failing.

2023-08-02 14:08 UTC, kamly commented
> Besides, one of the check is failing.

got it ,  I just want to push on and see what else I need to do

2023-08-02 14:10 UTC, nfrankel commented
>got it , I just want to push on and see what else I need to do

I appreciate your willingness to move forward and understand your eagerness to do more. Unfortunately, at the moment, all reviewers are busy.

As for me, I'm now on vacations. Please be patient.

2023-08-08 08:16 UTC, tao12345666333 requested changes

2023-08-08 08:16 UTC, tao12345666333 commented on centos/docker-entrypoint.sh
> +    fi
The indentation here is incorrect.

2023-08-11 01:24 UTC, kamly commented
@tao12345666333 fix~

2023-08-24 05:20 UTC, Revolyssup commented
@kamly one test still failing

2023-08-24 13:20 UTC, kamly commented
> @kamly one test still failing

I debugged the unit test and found that it will exit automatically. So executing curl http://127.0.0.1:9000/ will fail

![image](https://github.com/apache/apisix-docker/assets/15706085/971e59ee-26ca-443c-9e50-88b0428524a7)

I need help

2023-08-25 05:24 UTC, kamly commented
> @kamly one test still failing

fix it ~

2023-08-27 10:06 UTC, moonming commented
@tao12345666333 @Revolyssup please take a look this PR, thx

2023-08-27 10:27 UTC, Revolyssup requested changes

2023-08-27 10:27 UTC, Revolyssup commented on centos/docker-entrypoint.sh
> +        if [ ! -f "${PREFIX}/conf/apisix.yaml" ]; then
[This](https://github.com/apache/apisix-docker/pull/487/files#diff-8c251a9432dc64cc4a02088f433622d5bd6833832d0214fe045623021b226b92R25)  line is not protected by the if block so there will be override anyways. Shouldn't this if block moved upwards to protect the whole block?

2023-08-27 10:28 UTC, Revolyssup commented on centos/docker-entrypoint.sh
> +        if [ ! -f "${PREFIX}/conf/apisix.yaml" ]; then
cc: @kamly

2023-08-27 12:45 UTC, tao12345666333 approved these changes
LGTM

2023-08-28 05:02 UTC, kamly commented on centos/docker-entrypoint.sh
> +        if [ ! -f "${PREFIX}/conf/apisix.yaml" ]; then
> [This](https://github.com/apache/apisix-docker/pull/487/files#diff-8c251a9432dc64cc4a02088f433622d5bd6833832d0214fe045623021b226b92R25) line is not protected by the if block so there will be override anyways. Shouldn't this if block moved upwards to protect the whole block?

Do you mean: Can `conf/config.yaml` be overwritten ?

In my opinion, if `$APISIX_STAND_ALONE==true` is true, the content of `conf/config.yaml` should be reset

conf/config.yaml
```
deployment:
  role: data_plane	  
  role_data_plane:
    config_provider: yaml
```

2023-08-28 06:32 UTC, Revolyssup commented on centos/docker-entrypoint.sh
> +        if [ ! -f "${PREFIX}/conf/apisix.yaml" ]; then
[This](https://github.com/apache/apisix-docker/blob/126d19e3e1e6dad3467f9e815dcdace4d64a4cc0/debian/docker-entrypoint.sh#L32) is also being executed when `$APISIX_STAND_ALONE==true`.
From [here](https://github.com/apache/apisix-docker/blob/126d19e3e1e6dad3467f9e815dcdace4d64a4cc0/debian/docker-entrypoint.sh#L25) to [here](https://github.com/apache/apisix-docker/blob/126d19e3e1e6dad3467f9e815dcdace4d64a4cc0/debian/docker-entrypoint.sh#L36) is part of the same branch

2023-08-28 10:49 UTC, kamly commented on centos/docker-entrypoint.sh
> +        if [ ! -f "${PREFIX}/conf/apisix.yaml" ]; then
@Revolyssup I'm sorry, I don't quite understand what you mean, can you provide a demo?

my logic is:
when `$APISIX_STAND_ALONE==true` overwrite `conf/config.yaml`
then `! -f "${PREFIX}/conf/apisix.yaml"` is true overwrite `conf/apisix.yaml`

Only standalone need `conf/apisix.yaml`

2023-08-28 10:58 UTC, kamly commented on centos/docker-entrypoint.sh
> +        if [ ! -f "${PREFIX}/conf/apisix.yaml" ]; then
cc @tao12345666333 , I need help

2023-08-30 04:49 UTC, kamly commented on centos/docker-entrypoint.sh
> +        if [ ! -f "${PREFIX}/conf/apisix.yaml" ]; then
@Revolyssup hi?

2023-08-31 04:41 UTC, closed without merging

2023-08-31 04:44 UTC, Revolyssup commented
@kamly Why did you close it? 
My query was that this whole block is one if branch
``` bash
    if [ "$APISIX_STAND_ALONE" = "true" ]; then
        cat > ${PREFIX}/conf/config.yaml << _EOC_
deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
_EOC_

        cat > ${PREFIX}/conf/apisix.yaml << _EOC_
routes:
  -
#END
_EOC_
        /usr/bin/apisix init
```

But we were only add the extra protection on this code
``` bash
        cat > ${PREFIX}/conf/apisix.yaml << _EOC_
routes:
  -
#END
_EOC_
```

and not this
``` bash
        cat > ${PREFIX}/conf/config.yaml << _EOC_
deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
_EOC_
```

cc: @tao12345666333

2023-08-31 04:59 UTC, kamly commented
I made a mistake, I resubmit the PR