chore: remove etcdctl
apache/apisix-docker pull request #505
Opened 2023-09-26 07:24 UTC by shreemaan-abhishek

This PR: https://github.com/apache/apisix/pull/10015 removes the usage of etcdctl from APISIX due to this it's unnecessary to package etcdctl into apisix-base.

2023-09-26 07:31 UTC, monkeyDluffy6017 commented on debian/Dockerfile
> +    && rm /usr/local/openresty/bin/etcdctl \
Can we just remove the installation of `etcdctl` ?

2023-09-26 08:13 UTC, shreemaan-abhishek commented on debian/Dockerfile
> +    && rm /usr/local/openresty/bin/etcdctl \
that would be a breaking change. cc: @soulbird, @Sn0rt

2023-09-26 11:57 UTC, Sn0rt commented on debian/Dockerfile
> +    && rm /usr/local/openresty/bin/etcdctl \
@monkeyDluffy6017 LGTM, this easy to implementation. and it only for 3.6 and later version.

2023-09-27 02:05 UTC, leslie-tsang approved these changes

2023-09-27 02:13 UTC, monkeyDluffy6017 commented
Why are you only removing etcdctl from these 3 images? there are other images, like https://github.com/apache/apisix-docker/blob/master/all-in-one/apisix/Dockerfile

2023-09-27 02:41 UTC, monkeyDluffy6017 requested changes
Why are you only removing etcdctl from these 3 images? there are other images, like https://github.com/apache/apisix-docker/blob/master/all-in-one/apisix/Dockerfile and https://github.com/apache/apisix-docker/blob/master/all-in-one/apisix/Dockerfile

2023-09-27 03:47 UTC, monkeyDluffy6017 commented
@shreemaan-abhishek It looks like there are something wrong with the new commit

2023-09-27 10:28 UTC, monkeyDluffy6017 commented
@shreemaan-abhishek The ci still fails

2023-09-28 02:39 UTC, lingsamuel approved these changes
lgtm

2023-09-28 02:42 UTC, monkeyDluffy6017 approved these changes

2023-09-28 02:42 UTC, merged